fm_elfinder:
    assets_path: /components
    instances:
        files:
            include_assets: true
            relative_path: true
            editor: form
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: rush/files
        files_viewer:
            include_assets: true
            relative_path: true
            editor: form
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: rush/files
                        attributes:
                            - { pattern: '/(.*?)/', read: true, write: false, locked: true }
        gallery:
            include_assets: true
            relative_path: true
            editor: form
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: rush/gallery
                        upload_allow: ['all']
                        upload_deny: ['application/msword', 'application/pdf' ,'application/postscript', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
                        upload_max_size: 4M # also file upload sizes restricted in php.ini
        gallery_viewer:
            include_assets: true
            relative_path: true
            editor: form
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: rush/gallery
                        upload_allow: ['all']
                        upload_deny: ['application/msword', 'application/pdf' ,'application/postscript', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
                        upload_max_size: 4M # also file upload sizes restricted in php.ini