security:
    encoders:
        App\Entity\User:
            algorithm: auto
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    access_denied_url: /login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\ApiTokenAuthenticator
                entry_point: App\Security\LoginFormAuthenticator
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 86400
            switch_user: true
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot-password$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/efconnect, role: ROLE_VIEWER }
        - { path: ^/elfinder/files_viewer, role: ROLE_VIEWER }
        - { path: ^/elfinder/files, role: ROLE_MEDIA_MANAGEMENT_EDITOR }
        - { path: ^/elfinder/gallery_viewer, role: ROLE_VIEWER }
        - { path: ^/elfinder/gallery, role: ROLE_MEDIA_MANAGEMENT_EDITOR }
        - { path: ^/, roles: ROLE_VIEWER }
        # - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy:
        ROLE_VIEWER: [ROLE_USER_MANAGEMENT_VIEWER, ROLE_MEDIA_MANAGEMENT_VIEWER, ROLE_VISUAL_PACK_VIEWER, ROLE_PAGE_MANAGEMENT_VIEWER, ROLE_OBJECT_MENU_VIEWER, ROLE_OBJECT_CATEGORY_VIEWER, ROLE_OBJECT_PRODUCT_VIEWER]
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_VIEWER, ROLE_USER_MANAGEMENT_EDITOR,  ROLE_MEDIA_MANAGEMENT_EDITOR,  ROLE_ROLES_MANAGEMENT,  ROLE_VISUAL_PACK_EDITOR,  ROLE_PAGE_MANAGEMENT_EDITOR, ROLE_BO_SETTINGS, ROLE_API_USER, ROLE_OBJECT_MENU_EDITOR, ROLE_OBJECT_CATEGORY_EDITOR, ROLE_OBJECT_PRODUCT_EDITOR ]
